version: '3'
services:
  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  service:
    build: service
    image: image-search/service:0.1
    ports:
      - "8000:80"
    volumes:
      - image_storage:/storage/media/
      - "./service/:/app/"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ALLOW_INPUT: ${ALLOW_INPUT}

volumes:
  postgres-data:
  image_storage:
