# Generated by Django 2.2.7 on 2019-11-13 16:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='FaceIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('face_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ImageIndex')),
            ],
        ),
    ]
